apiVersion: v1
kind: Ruleset
name: default
spec:
  enforcement: evaluate
  bypassapps:
    - appname: goliac-project-app
      mode: always
  on:
    include: 
      - "~DEFAULT_BRANCH"

  rules:
    - ruletype: pull_request
      parameters:
        requiredApprovingReviewCount: 1
