apiVersion: v1
kind: Repository
name: goliac
spec:
  visibility: public
  rulesets:
    - enforcement: active
      conditions:
        include:
          - ~DEFAULT_BRANCH
      rules:
        - ruletype: deletion
        - ruletype: non_fast_forward
        - ruletype: pull_request
      name: main

