name: Validate structure

on: [pull_request]

jobs:
  build:
    name: validate

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify
        run: docker run -v ${{ github.workspace }}:/work --rm ghcr.io/nzin/goliac verify /work

